### ISSUE TITLE
Not compatible with Safari at all ?

### ISSUE THREAD

**Issue by brainra** [weblinc/jquery.smoothState.js#120]
Hi, I've been using smoothState for the past few days, and when I tested my project on Safari, blank screen. Same with demos, and same with your project homepage : http://weblinc.github.io/jquery.smoothState.js/

What is going on ?

Using Safari 8.0.3, and my css has prefixes. The issue seems to be coming from the animations though ?

**Comment by brainra** [comment]
My bad

**Comment by mhokane** [comment]
Having the same issue in Safari on my own page and on the SmoothState page. @brainra did you find a fix?

**Comment by brainra** [comment]
@mhokane I think it was related to Yosemite somehow. As far as I remember, the moment I restarted my macbook, the issue was gone.

**Comment by Jonathlee** [comment]
@brainra I tested my site with Mac Pro, did stumble the situation as well. But after restarting the Macbook, the bug seems to be gone. No problem with Chrome or Firefox though...

**Comment by brainra** [comment]
![image](https://cloud.githubusercontent.com/assets/2838256/11179069/248631f0-8c51-11e5-98bd-8d47711c961d.png)

**Comment by miguel-perez** [comment]
lol, get everything sorted out @brainra?

**Comment by brainra** [comment]
Yes @miguel-perez, problem is solved for me, some other developers seem to encounter the problem but restarting appears to help !

**Comment by mhokane** [comment]
Restarting worked :) Just seeing this now.
